/*
 * @Author: peter
 * @Date: 2017-10-12 10:13:29
 * @Last Modified by: peter
 * @Last Modified time: 2017-12-18 16:49:13
 */
// 全局的mutations-type类型
export const SAVE_USERINFO = 'SAVE_USERINFO';

export const SAVE_PRODUCTMD_INFO = 'SAVE_PRODUCTMD_INFO';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const ADD_NEW_TAG = 'ADD_NEW_TAG';

export const REMOVE_TAG = 'REMOVE_TAG';

export const SET_TAG = 'SET_TAG';

export const SAVE_SITE_SALES_CHART = 'SAVE_SITE_SALES_CHART';

export const SAVE_PERSONNEL_COMPARISON_CHART = 'SAVE_PERSONNEL_COMPARISON_CHART';

export const SAVE_PERSONNEL_PLATFORM_CHART = 'SAVE_PERSONNEL_PLATFORM_CHART';

export const SAVE_PLATFORM_PERSONNEL_PLATFORM_CHART = 'SAVE_PLATFORM_PERSONNEL_PLATFORM_CHART';

export const SAVE_PERSONNEL_SALES_CHART = 'SAVE_PERSONNEL_SALES_CHART';

export const SAVE_PERSONNEL_PROFIT_AND_LOSS_CHART = 'SAVE_PERSONNEL_PROFIT_AND_LOSS_CHART';

export const SAVE_ORDER_ONE_ORDER_INFO = 'SAVE_ORDER_ONE_ORDER_INFO';

export const SAVE_ORDER_ONE_MANAGE_LIST_INFO = 'SAVE_ORDER_ONE_MANAGE_LIST_INFO';

export const SAVE_PRODUCT_INFO = 'SAVE_PRODUCT_INFO';

export const SAVE_SHOW_CHART_AUTHORITY = 'SAVE_SHOW_CHART_AUTHORITY';

export const CHANGE_SHOW_CHART_STATUS = 'CHANGE_SHOW_CHART_STATUS';

export const SAVE_SITE_SALES_DETAIL_CHART = 'SAVE_SITE_SALES_DETAIL_CHART';
